### ISSUE TITLE
unable to use aws-sdk-rust on actix project, thread panics

### ISSUE THREAD

**Issue by doums** [awslabs/aws-sdk-rust#132]
### Version
- actix 4.0.0-beta.8
- aws-sdk-rust v0.0.9-alpha
- tokio ^1

### Platform
`Linux mitx 5.12.13-arch1-2 #1 SMP PREEMPT Fri, 25 Jun 2021 22:56:51 +0000 x86_64 GNU/Linux`

### AWS Services

s3

### Description

Hi,

I'm working on an API built with actix-web and I try to use aws-sdk-rust. Here is my code
```rust
mod service_config;
// ...

const HOST: &str = "localhost";
const PORT: u32 = 4000;
const S3_HOST: &str = "http://localhost:9000";
const AWS_ACCESS_KEY_ID: &str = "minio";
const AWS_SECRET_ACCESS_KEY: &str = "minio123";

#[derive(Debug)]
struct AppState {
    s3: s3::Client,
}

impl AppState {
    fn new(client: s3::Client) -> Self {
        AppState { s3: client }
    }
}

struct CredentialsProvider;

impl ProvideCredentials for CredentialsProvider {
    fn provide_credentials(&self) -> Result<Credentials, CredentialsError> {
        Ok(Credentials::from_keys(
            AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY,
            None,
        ))
    }
}

#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
    set_var("RUST_LOG", "debug,actix_web=debug");
    env_logger::init();
    let region = Region::new("eu-west-3");
    let s3_config = Config::builder()
        .region(region)
        .endpoint_resolver(Endpoint::immutable(Uri::from_static(S3_HOST)))
        .credentials_provider(CredentialsProvider)
        .build();
    let client = s3::Client::from_conf(s3_config);
    let app_state = web::Data::new(AppState::new(client));

    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = System::new();
        let srv = HttpServer::new(move || {
            App::new()
                .wrap(Logger::new("%r -> [%s] took %Tms"))
                .app_data(app_state.clone())
                .configure(config) // config is a simple route that does nothing
        })
        .bind(format!("{}:{}", HOST, PORT))?
        .shutdown_timeout(5)
        .run();

        let _ = tx.send(srv);
        info!("🦀 running on port {} 🦀", PORT);
        sys.run()
    });

    let srv = rx.recv().unwrap();
    srv.await?;
    info!("gracefully shutdown");
    Ok(())
}
```
When I run the app there is a thread panic, see the logs
```
[2021-06-28T15:44:28Z DEBUG rustls::anchors] add_pem_file processed 128 valid and 0 invalid certs
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting 8 workers
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting "actix-web-service-[::1]:4000" service on [::1]:4000
[2021-06-28T15:44:28Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:4000" service on 127.0.0.1:4000
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/context.rs:28:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/main.rs:79:25
```
I suppose there is some conflict about versions of tokio used by actix and aws-sdk-rust ?

**Comment by rcoh** [comment]
the output of `cargo tree` would be very helpful here, but assuming nothing has changed since #87, I think your assessment is correct.

**Comment by doums** [comment]
tokio
```
 cargo tree | rg tokio
│   │   ├── tokio v1.7.1
│   │   │   └── tokio-macros v1.2.0 (proc-macro)
│   │   └── tokio-util v0.6.7
│   │       └── tokio v1.7.1 (*)
│   │   │   └── tokio v1.7.1 (*)
│   │   │   └── tokio-util v0.6.7 (*)
│   │   │   ├── tokio v1.7.1 (*)
│   │   │   ├── tokio-util v0.6.7 (*)
│   │   ├── tokio v1.7.1 (*)
│   │   └── tokio v1.7.1 (*)
│   │   │   ├── tokio v1.7.1 (*)
│   │   ├── tokio v1.7.1 (*)
│   │   ├── tokio-util v0.6.7 (*)
│   │   │   ├── tokio v1.7.1 (*)
│   │   │   ├── tokio-rustls v0.22.0
│   │   │   │   ├── tokio v1.7.1 (*)
│   │   │   │   │   ├── tokio v1.7.1 (*)
│   │   │   ├── tokio v1.7.1 (*)
│   │   ├── tokio v1.7.1 (*)
└── tokio v1.7.1 (*)
```
aws-sdk
```
cargo tree | rg aws-sdk
├── aws-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   ├── smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
├── aws-sdk-s3 v0.0.9-alpha (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   ├── aws-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── aws-endpoint v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   ├── aws-types v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   └── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── aws-http v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   ├── aws-types v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── aws-hyper v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   ├── aws-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── aws-endpoint v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── aws-http v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── aws-sig-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   │   ├── aws-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   │   ├── aws-types v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   │   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── protocol-test-helpers v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   ├── smithy-client v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   │   ├── protocol-test-helpers v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   │   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   │   ├── smithy-http-tower v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
│   │   │   │   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   │   ├── smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── smithy-http-tower v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   │   ├── smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── aws-sig-auth v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── aws-types v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   ├── smithy-types v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
│   └── smithy-xml v0.1.0 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53)
├── smithy-http v0.0.1 (https://github.com/awslabs/aws-sdk-rust?tag=v0.0.9-alpha#52164d53) (*)
```

**Comment by rcoh** [comment]
I'm not totally familiar with the way that actix works, but it seems like it isn't starting a tokio runtime. You could try starting one manually? Let me ask around

**Comment by eagletmt** [comment]
The thread panic doesn't seem to have anything to do with aws-sdk-rust. I could reproduce the same error without aws-sdk-rust.

```rust
#[actix_web::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (tx, rx) = std::sync::mpsc::channel();

    std::thread::spawn(move || {
        let sys = actix_web::rt::System::new();
        let srv = actix_web::HttpServer::new(actix_web::App::new)
            .bind("localhost:4000")
            .unwrap()
            .run();
        let _ = tx.send(srv);
        sys.run()
    });

    let srv = rx.recv()?;
    srv.await?;

    Ok(())
}
```

```
% cargo run
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/eagletmt/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/context.rs:28:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: RecvError
```

It seems you're missing `sys.block_on()` to run HttpServer in spawned thread.

```rust
#[actix_web::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (tx, rx) = std::sync::mpsc::channel();

    std::thread::spawn(move || {
        let sys = actix_web::rt::System::new();
        // https://github.com/actix/actix-web/blob/web-v4.0.0-beta.8/tests/test_httpserver.rs
        sys.block_on(async {
            let srv = actix_web::HttpServer::new(actix_web::App::new)
                .bind("localhost:4000")
                .unwrap()
                .run();
            let _ = tx.send(srv);
        });
        sys.run()
    });

    let srv = rx.recv()?;
    srv.await?;

    Ok(())
}
```

```
% cargo run &
% curl -D- localhost:4000
HTTP/1.1 404 Not Found
content-length: 0
date: Wed, 30 Jun 2021 07:13:07 GMT
```

**Comment by doums** [comment]
Hi, thanks @eagletmt ! I confirm, the panics is fixed with the following code
```
#[actix_web::main]
async fn main() -> Result<(), Box<dyn Error>> {
    set_var("RUST_LOG", "debug,actix_web=debug");
    env_logger::init();
    let region = Region::new("eu-west-3");
    let s3_config = Config::builder()
        .region(region)
        .endpoint_resolver(Endpoint::immutable(Uri::from_static(S3_HOST)))
        .credentials_provider(CredentialsProvider)
        .build();
    let client = s3::Client::from_conf(s3_config);
    let app_state = web::Data::new(AppState::new(client));

    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = System::new();
        sys.block_on(async {
            let srv = HttpServer::new(move || {
                App::new()
                    .wrap(Logger::new("%r -> [%s] took %Tms"))
                    .app_data(app_state.clone())
                    .configure(config)
            })
            .bind(format!("{}:{}", HOST, PORT))
            .unwrap()
            .shutdown_timeout(5)
            .run();

            let _ = tx.send(srv);
        });
        info!("🦀 archivur running on port {} 🦀", PORT);
        sys.run()
    });

    let srv = rx.recv().unwrap();
    srv.await?;
    info!("archivur gracefully shutdown");
    Ok(())
}
```
